import type { ProductionCycleStageId, ProductionCycleStageMeta } from './types'

export const PRODUCTION_CYCLE_STAGE_META: Record<ProductionCycleStageId, ProductionCycleStageMeta> = {
  recipe: {
    id: 'recipe',
    titleKey: 'productionCycle.stage.recipe',
    viewId: 'technologist',
    viewLabelKey: 'productionCycle.view.technologist',
    responsibleRoleIds: ['technologist', 'chief_engineer'],
    actionKey: 'productionCycle.action.recipe',
  },
  procurement: {
    id: 'procurement',
    titleKey: 'productionCycle.stage.procurement',
    viewId: 'procurement',
    viewLabelKey: 'productionCycle.view.procurement',
    responsibleRoleIds: ['procurement_manager'],
    actionKey: 'productionCycle.action.procurement',
  },
  receipt: {
    id: 'receipt',
    titleKey: 'productionCycle.stage.receipt',
    viewId: 'warehouse',
    viewLabelKey: 'productionCycle.view.warehouse',
    responsibleRoleIds: ['warehouse_keeper'],
    actionKey: 'productionCycle.action.receipt',
  },
  production_order: {
    id: 'production_order',
    titleKey: 'productionCycle.stage.production_order',
    viewId: 'planner',
    viewLabelKey: 'productionCycle.view.planner',
    responsibleRoleIds: ['chief_engineer', 'operations_director'],
    actionKey: 'productionCycle.action.production_order',
  },
  material_issue: {
    id: 'material_issue',
    titleKey: 'productionCycle.stage.material_issue',
    viewId: 'warehouse',
    viewLabelKey: 'productionCycle.view.warehouse',
    responsibleRoleIds: ['warehouse_keeper'],
    actionKey: 'productionCycle.action.material_issue',
  },
  mixer: {
    id: 'mixer',
    titleKey: 'productionCycle.stage.mixer',
    viewId: 'mixer',
    viewLabelKey: 'productionCycle.view.mixer',
    responsibleRoleIds: ['mixer'],
    actionKey: 'productionCycle.action.mixer',
  },
  impregnation: {
    id: 'impregnation',
    titleKey: 'productionCycle.stage.impregnation',
    viewId: 'technologist',
    viewLabelKey: 'productionCycle.view.technologist',
    responsibleRoleIds: ['technologist'],
    actionKey: 'productionCycle.action.impregnation',
  },
  line: {
    id: 'line',
    titleKey: 'productionCycle.stage.line',
    viewId: 'production',
    viewLabelKey: 'productionCycle.view.production',
    responsibleRoleIds: ['workshop_master'],
    actionKey: 'productionCycle.action.line',
  },
  packaging: {
    id: 'packaging',
    titleKey: 'productionCycle.stage.packaging',
    viewId: 'production',
    viewLabelKey: 'productionCycle.view.production',
    responsibleRoleIds: ['workshop_master'],
    actionKey: 'productionCycle.action.packaging',
  },
  otc: {
    id: 'otc',
    titleKey: 'productionCycle.stage.otc',
    viewId: 'otc',
    viewLabelKey: 'productionCycle.view.otc',
    responsibleRoleIds: ['otc'],
    actionKey: 'productionCycle.action.otc',
  },
  sales: {
    id: 'sales',
    titleKey: 'productionCycle.stage.sales',
    viewId: 'director',
    viewLabelKey: 'productionCycle.view.director',
    responsibleRoleIds: ['operations_director', 'sales_dispatcher'],
    actionKey: 'productionCycle.action.sales',
  },
  loading: {
    id: 'loading',
    titleKey: 'productionCycle.stage.loading',
    viewId: 'warehouse',
    viewLabelKey: 'productionCycle.view.warehouse',
    responsibleRoleIds: ['warehouse_keeper'],
    actionKey: 'productionCycle.action.loading',
  },
  shipment: {
    id: 'shipment',
    titleKey: 'productionCycle.stage.shipment',
    viewId: 'warehouse',
    viewLabelKey: 'productionCycle.view.warehouse',
    responsibleRoleIds: ['warehouse_keeper'],
    actionKey: 'productionCycle.action.shipment',
  },
}
