# FST — деплой Firebase (Firestore + Hosting) и переменные в Vercel
# Запуск из PowerShell после: firebase login

$ErrorActionPreference = "Stop"
$Root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$Web = Join-Path $Root "fst-web"
$ProjectId = "fst-uchet"

Set-Location $Web

Write-Host "=== FST cloud deploy ===" -ForegroundColor Cyan

firebase projects:list | Out-Null
if ($LASTEXITCODE -ne 0) {
  Write-Host "Сначала выполните: firebase login --reauth" -ForegroundColor Red
  exit 1
}

$exists = firebase projects:list 2>$null | Select-String $ProjectId
if (-not $exists) {
  Write-Host "Создаю проект Firebase: $ProjectId"
  firebase projects:create $ProjectId --display-name "FST Uchet"
}

firebase use $ProjectId

Write-Host "Firestore..."
$db = firebase firestore:databases:list 2>$null | Select-String "\(default\)"
if (-not $db) {
  firebase firestore:databases:create "(default)" --location=europe-west3
}

Write-Host "Web app + ключи..."
$apps = firebase apps:list WEB 2>$null
if ($apps -notmatch "App ID") {
  firebase apps:create WEB "FST Web" --project $ProjectId
}

$sdk = firebase apps:sdkconfig WEB --project $ProjectId 2>&1 | Out-String
if ($sdk -notmatch "apiKey") {
  Write-Host "Не удалось получить sdkconfig. Создайте Web app в Firebase Console." -ForegroundColor Yellow
  exit 1
}

function Get-SdkValue($key) {
  if ($sdk -match "$key`: `"([^`"]+)`"") { return $Matches[1] }
  return ""
}

$envMap = @{
  VITE_FIREBASE_API_KEY            = Get-SdkValue "apiKey"
  VITE_FIREBASE_AUTH_DOMAIN        = Get-SdkValue "authDomain"
  VITE_FIREBASE_PROJECT_ID         = Get-SdkValue "projectId"
  VITE_FIREBASE_STORAGE_BUCKET     = Get-SdkValue "storageBucket"
  VITE_FIREBASE_MESSAGING_SENDER_ID = Get-SdkValue "messagingSenderId"
  VITE_FIREBASE_APP_ID             = Get-SdkValue "appId"
}

$envFile = Join-Path $Web ".env"
@"
# Auto-generated by deploy-cloud.ps1
VITE_FIREBASE_API_KEY=$($envMap.VITE_FIREBASE_API_KEY)
VITE_FIREBASE_AUTH_DOMAIN=$($envMap.VITE_FIREBASE_AUTH_DOMAIN)
VITE_FIREBASE_PROJECT_ID=$($envMap.VITE_FIREBASE_PROJECT_ID)
VITE_FIREBASE_STORAGE_BUCKET=$($envMap.VITE_FIREBASE_STORAGE_BUCKET)
VITE_FIREBASE_MESSAGING_SENDER_ID=$($envMap.VITE_FIREBASE_MESSAGING_SENDER_ID)
VITE_FIREBASE_APP_ID=$($envMap.VITE_FIREBASE_APP_ID)
"@ | Set-Content -Encoding UTF8 $envFile

Write-Host "Сборка fst-web..."
Set-Location $Root
npm run build:fst-web

Write-Host "Firestore rules + Hosting..."
Set-Location $Web
firebase deploy --only firestore,hosting --project $ProjectId

Write-Host "Vercel env + redeploy..."
Set-Location $Root
foreach ($pair in $envMap.GetEnumerator()) {
  if ($pair.Value) {
    Write-Host "  $($pair.Key)"
    echo $pair.Value | vercel env add $pair.Key production --force 2>$null
    echo $pair.Value | vercel env add $pair.Key preview --force 2>$null
    echo $pair.Value | vercel env add $pair.Key development --force 2>$null
  }
}

vercel --prod --yes

Write-Host ""
Write-Host "Готово!" -ForegroundColor Green
Write-Host "Vercel:  https://fst-uchet.vercel.app"
Write-Host "Firebase Hosting: https://${ProjectId}.web.app"
Write-Host ""
Write-Host "В Firebase Console включите Authentication -> Email/Password (если ещё не включено)."
