# FST - setup Firebase Firestore (project: fst-uchet)
# FBeda project fbeda-5c061 is NOT used here.
# Run: npm run setup:firebase
# Requires: firebase login

$ErrorActionPreference = "Stop"
$Web = Split-Path $PSScriptRoot -Parent
$ProjectId = "fst-uchet-14c02"
$Location = "europe-west3"

Set-Location $Web

Write-Host "=== FST Firebase Firestore setup ===" -ForegroundColor Cyan
Write-Host "Project: $ProjectId (NOT fbeda-5c061)"
Write-Host ""

firebase projects:list | Out-Null
if ($LASTEXITCODE -ne 0) {
  Write-Host "Run first: firebase login" -ForegroundColor Red
  exit 1
}

$exists = firebase projects:list 2>$null | Select-String $ProjectId
if (-not $exists) {
  Write-Host "Creating Firebase project: $ProjectId ..."
  firebase projects:create $ProjectId --display-name "FST Uchet"
  if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "Could not create project (quota or permissions)." -ForegroundColor Red
    Write-Host "Options:"
    Write-Host "  1. Delete an unused Firebase project in console"
    Write-Host "  2. Create fst-uchet manually: https://console.firebase.google.com/"
    Write-Host "  3. Then run this script again"
    exit 1
  }
}

firebase use $ProjectId
if ($LASTEXITCODE -ne 0) { exit 1 }

Write-Host "[1/5] Firestore database..."
$db = firebase firestore:databases:list --project $ProjectId 2>$null | Select-String "\(default\)"
if (-not $db) {
  Write-Host "  Creating (default) in $Location..."
  firebase firestore:databases:create "(default)" --location=$Location --project $ProjectId
  if ($LASTEXITCODE -ne 0) { exit 1 }
} else {
  Write-Host "  Database (default) exists." -ForegroundColor Green
}

Write-Host "[2/5] Security rules..."
firebase deploy --only firestore:rules --project $ProjectId
if ($LASTEXITCODE -ne 0) { exit 1 }

Write-Host "[3/5] Web app + SDK keys..."
$apps = firebase apps:list WEB --project $ProjectId 2>&1 | Out-String
if ($apps -notmatch "App ID") {
  firebase apps:create WEB "FST Web" --project $ProjectId
}

$sdk = firebase apps:sdkconfig WEB --project $ProjectId 2>&1 | Out-String
if ($sdk -notmatch "apiKey") {
  Write-Host "Create Web app in Firebase Console, then re-run." -ForegroundColor Yellow
  exit 1
}

function Get-SdkValue($key) {
  if ($sdk -match "$key`: `"([^`"]+)`"") { return $Matches[1] }
  return ""
}

$envMap = @{
  VITE_FIREBASE_API_KEY             = Get-SdkValue "apiKey"
  VITE_FIREBASE_AUTH_DOMAIN         = Get-SdkValue "authDomain"
  VITE_FIREBASE_PROJECT_ID          = Get-SdkValue "projectId"
  VITE_FIREBASE_STORAGE_BUCKET      = Get-SdkValue "storageBucket"
  VITE_FIREBASE_MESSAGING_SENDER_ID = Get-SdkValue "messagingSenderId"
  VITE_FIREBASE_APP_ID              = Get-SdkValue "appId"
}

Write-Host "[4/5] Writing .env..."
$envFile = Join-Path $Web ".env"
@"
# Auto-generated by setup-firebase-db.ps1 (project fst-uchet)
VITE_FIREBASE_API_KEY=$($envMap.VITE_FIREBASE_API_KEY)
VITE_FIREBASE_AUTH_DOMAIN=$($envMap.VITE_FIREBASE_AUTH_DOMAIN)
VITE_FIREBASE_PROJECT_ID=$($envMap.VITE_FIREBASE_PROJECT_ID)
VITE_FIREBASE_STORAGE_BUCKET=$($envMap.VITE_FIREBASE_STORAGE_BUCKET)
VITE_FIREBASE_MESSAGING_SENDER_ID=$($envMap.VITE_FIREBASE_MESSAGING_SENDER_ID)
VITE_FIREBASE_APP_ID=$($envMap.VITE_FIREBASE_APP_ID)
"@ | Set-Content -Encoding UTF8 $envFile

Copy-Item $envFile (Join-Path $Web ".env.production") -Force

Write-Host "[5/5] Schema:"
Write-Host "  Collection: fstStores"
Write-Host "  Document:   fstStores/<user-uid>"
Write-Host ""

Write-Host "Done!" -ForegroundColor Green
Write-Host "Enable Auth Email/Password in Console, create admin user."
Write-Host "Console: https://console.firebase.google.com/project/$ProjectId/firestore"
