/** ISO 3166-1 alpha-2 + названия (полный список государств) */
export type CountryEntry = { code: string; ru: string; ka: string }

export const COUNTRIES: CountryEntry[] = [
  { code: 'AU', ru: 'Австралия', ka: 'ავსტრალია' },
  { code: 'AT', ru: 'Австрия', ka: 'ავსტრია' },
  { code: 'AZ', ru: 'Азербайджан', ka: 'აზერბაიჯანი' },
  { code: 'AL', ru: 'Албания', ka: 'ალბანეთი' },
  { code: 'DZ', ru: 'Алжир', ka: 'ალჟირი' },
  { code: 'AO', ru: 'Ангола', ka: 'ანგოლა' },
  { code: 'AD', ru: 'Андорра', ka: 'ანდორა' },
  { code: 'AG', ru: 'Антигуа и Барбуда', ka: 'ანტიგუა და ბარბუდა' },
  { code: 'AR', ru: 'Аргентина', ka: 'არგენტინა' },
  { code: 'AM', ru: 'Армения', ka: 'სომხეთი' },
  { code: 'AF', ru: 'Афганистан', ka: 'ავღანეთი' },
  { code: 'BS', ru: 'Багамские Острова', ka: 'ბაჰამის კუნძულები' },
  { code: 'BD', ru: 'Бангладеш', ka: 'ბანგლადეში' },
  { code: 'BB', ru: 'Барбадос', ka: 'ბარბადოსი' },
  { code: 'BH', ru: 'Бахрейн', ka: 'ბაჰრეინი' },
  { code: 'BY', ru: 'Беларусь', ka: 'ბელარუსი' },
  { code: 'BE', ru: 'Бельгия', ka: 'ბელგია' },
  { code: 'BZ', ru: 'Белиз', ka: 'ბელიზი' },
  { code: 'BJ', ru: 'Бенин', ka: 'ბენინი' },
  { code: 'BG', ru: 'Болгария', ka: 'ბულგარეთი' },
  { code: 'BO', ru: 'Боливия', ka: 'ბოლივია' },
  { code: 'BA', ru: 'Босния и Герцеговина', ka: 'ბოსნია და ჰერცეგოვინა' },
  { code: 'BW', ru: 'Ботсвана', ka: 'ბოტსვანა' },
  { code: 'BR', ru: 'Бразилия', ka: 'ბრაზილია' },
  { code: 'BN', ru: 'Бруней', ka: 'ბრუნეი' },
  { code: 'BF', ru: 'Буркина-Фасо', ka: 'ბურკინა-ფასო' },
  { code: 'BI', ru: 'Бурунди', ka: 'ბურუნდი' },
  { code: 'BT', ru: 'Бутан', ka: 'ბუტანი' },
  { code: 'VU', ru: 'Вануату', ka: 'ვანუატუ' },
  { code: 'GB', ru: 'Великобритания', ka: 'გაერთიანებული სამეფო' },
  { code: 'HU', ru: 'Венгрия', ka: 'უნგრეთი' },
  { code: 'VE', ru: 'Венесуэла', ka: 'ვენესუელა' },
  { code: 'TL', ru: 'Восточный Тимор', ka: 'აღმოსავეთი ტიმორი' },
  { code: 'VN', ru: 'Вьетнам', ka: 'ვიეტნამი' },
  { code: 'GA', ru: 'Габон', ka: 'გაბონი' },
  { code: 'HT', ru: 'Гаити', ka: 'ჰაიტი' },
  { code: 'GY', ru: 'Гайана', ka: 'გაიანა' },
  { code: 'GM', ru: 'Гамбия', ka: 'გამბია' },
  { code: 'GH', ru: 'Гана', ka: 'განა' },
  { code: 'GT', ru: 'Гватемала', ka: 'გვატემალა' },
  { code: 'GN', ru: 'Гвинея', ka: 'გვინეა' },
  { code: 'GW', ru: 'Гвинея-Бисау', ka: 'გვინეა-ბისაუ' },
  { code: 'DE', ru: 'Германия', ka: 'გერმანია' },
  { code: 'HN', ru: 'Гондурас', ka: 'ჰონდურასი' },
  { code: 'GD', ru: 'Гренада', ka: 'გრენადა' },
  { code: 'GR', ru: 'Греция', ka: 'საბერძნეთი' },
  { code: 'GE', ru: 'Грузия', ka: 'საქართველო' },
  { code: 'DK', ru: 'Дания', ka: 'დანია' },
  { code: 'CD', ru: 'ДР Конго', ka: 'კონგოს დემოკრატიული რესპუბლიკა' },
  { code: 'DJ', ru: 'Джибути', ka: 'ჯიბუტი' },
  { code: 'DM', ru: 'Доминика', ka: 'დომინიკა' },
  { code: 'DO', ru: 'Доминиканская Республика', ka: 'დომინიკანის რესპუბლიკა' },
  { code: 'EG', ru: 'Египет', ka: 'ეგვიპტე' },
  { code: 'ZM', ru: 'Замбия', ka: 'ზამბია' },
  { code: 'ZW', ru: 'Зимбабве', ka: 'ზიმბაბვე' },
  { code: 'IL', ru: 'Израиль', ka: 'ისრაელი' },
  { code: 'IN', ru: 'Индия', ka: 'ინდოეთი' },
  { code: 'ID', ru: 'Индонезия', ka: 'ინდონეზია' },
  { code: 'JO', ru: 'Иордания', ka: 'იორდანია' },
  { code: 'IQ', ru: 'Ирак', ka: 'ერაყი' },
  { code: 'IR', ru: 'Иран', ka: 'ირანი' },
  { code: 'IE', ru: 'Ирландия', ka: 'ირლანდია' },
  { code: 'IS', ru: 'Исландия', ka: 'ისლანდია' },
  { code: 'ES', ru: 'Испания', ka: 'ესპანეთი' },
  { code: 'IT', ru: 'Италия', ka: 'იტალია' },
  { code: 'YE', ru: 'Йемен', ka: 'იემენი' },
  { code: 'CV', ru: 'Кабо-Верде', ka: 'კაბო-ვერდე' },
  { code: 'KZ', ru: 'Казахстан', ka: 'ყაზახეთი' },
  { code: 'KH', ru: 'Камбоджа', ka: 'კამბოჯა' },
  { code: 'CM', ru: 'Камерун', ka: 'კამერუნი' },
  { code: 'CA', ru: 'Канада', ka: 'კანადა' },
  { code: 'QA', ru: 'Катар', ka: 'კატარი' },
  { code: 'KE', ru: 'Кения', ka: 'კენია' },
  { code: 'CY', ru: 'Кипр', ka: 'კვიპროსი' },
  { code: 'KG', ru: 'Киргизия', ka: 'ყირგიზეთი' },
  { code: 'KI', ru: 'Кирибати', ka: 'კირიბატი' },
  { code: 'CN', ru: 'Китай', ka: 'ჩინეთი' },
  { code: 'CO', ru: 'Колумбия', ka: 'კოლუმბია' },
  { code: 'KM', ru: 'Коморские Острова', ka: 'კომორის კუნძულები' },
  { code: 'CG', ru: 'Конго', ka: 'კონგო' },
  { code: 'CR', ru: 'Коста-Рика', ka: 'კოსტა-რიკა' },
  { code: 'CI', ru: "Кот-д'Ивуар", ka: 'კოტ-დივუარი' },
  { code: 'CU', ru: 'Куба', ka: 'კუბა' },
  { code: 'KW', ru: 'Кувейт', ka: 'ქუვეითი' },
  { code: 'LA', ru: 'Лаос', ka: 'ლაოსი' },
  { code: 'LV', ru: 'Латвия', ka: 'ლატვია' },
  { code: 'LS', ru: 'Лесото', ka: 'ლესოთო' },
  { code: 'LR', ru: 'Либерия', ka: 'ლიბერია' },
  { code: 'LB', ru: 'Ливан', ka: 'ლიბანი' },
  { code: 'LY', ru: 'Ливия', ka: 'ლიბია' },
  { code: 'LT', ru: 'Литва', ka: 'ლიტვა' },
  { code: 'LI', ru: 'Лихтенштейн', ka: 'ლიხტენშტაინი' },
  { code: 'LU', ru: 'Люксембург', ka: 'ლუქსემბურგი' },
  { code: 'MU', ru: 'Маврикий', ka: 'მავრიკი' },
  { code: 'MR', ru: 'Мавритания', ka: 'მავრიტანია' },
  { code: 'MG', ru: 'Мадагаскар', ka: 'მადაგასკარი' },
  { code: 'MW', ru: 'Малави', ka: 'მალავი' },
  { code: 'MY', ru: 'Малайзия', ka: 'მალაიზია' },
  { code: 'ML', ru: 'Мали', ka: 'მალი' },
  { code: 'MV', ru: 'Мальдивы', ka: 'მალდივები' },
  { code: 'MT', ru: 'Мальта', ka: 'მალტა' },
  { code: 'MA', ru: 'Марокко', ka: 'მაროკო' },
  { code: 'MH', ru: 'Маршалловы Острова', ka: 'მარშალის კუნძულები' },
  { code: 'MX', ru: 'Мексика', ka: 'მექსიკა' },
  { code: 'MZ', ru: 'Мозамбик', ka: 'მოზამბიკი' },
  { code: 'MD', ru: 'Молдова', ka: 'მოლდოვა' },
  { code: 'MC', ru: 'Монако', ka: 'მონაკო' },
  { code: 'MN', ru: 'Монголия', ka: 'მონღოლეთი' },
  { code: 'MM', ru: 'Мьянма', ka: 'მიანმა' },
  { code: 'NA', ru: 'Намибия', ka: 'ნამიბია' },
  { code: 'NR', ru: 'Науру', ka: 'ნაურუ' },
  { code: 'NP', ru: 'Непал', ka: 'ნეპალი' },
  { code: 'NE', ru: 'Нигер', ka: 'ნიგერი' },
  { code: 'NG', ru: 'Нигерия', ka: 'ნიგერია' },
  { code: 'NL', ru: 'Нидерланды', ka: 'ნიდერლანდები' },
  { code: 'NI', ru: 'Никарагуа', ka: 'ნიკარაგუა' },
  { code: 'NZ', ru: 'Новая Зеландия', ka: 'ახალი ზელანდია' },
  { code: 'NO', ru: 'Норвегия', ka: 'ნორვეგია' },
  { code: 'AE', ru: 'ОАЭ', ka: 'არაბთა გაერთიანებული საამიროები' },
  { code: 'OM', ru: 'Оман', ka: 'ომანი' },
  { code: 'PK', ru: 'Пакистан', ka: 'პაკისტანი' },
  { code: 'PW', ru: 'Палау', ka: 'პალაუ' },
  { code: 'PA', ru: 'Панама', ka: 'პანამა' },
  { code: 'PG', ru: 'Папуа — Новая Гвинея', ka: 'პაპუა ახალი გვინეა' },
  { code: 'PY', ru: 'Парагвай', ka: 'პარაგვაი' },
  { code: 'PE', ru: 'Перу', ka: 'პერუ' },
  { code: 'PL', ru: 'Польша', ka: 'პოლონეთი' },
  { code: 'PT', ru: 'Португалия', ka: 'პორტუგალია' },
  { code: 'KR', ru: 'Республика Корея', ka: 'სამხრეთ კორეა' },
  { code: 'RU', ru: 'Россия', ka: 'რუსეთი' },
  { code: 'RW', ru: 'Руанда', ka: 'რუანდა' },
  { code: 'RO', ru: 'Румыния', ka: 'რუმინეთი' },
  { code: 'SV', ru: 'Сальвадор', ka: 'სალვადორი' },
  { code: 'WS', ru: 'Самоа', ka: 'სამოა' },
  { code: 'SM', ru: 'Сан-Марино', ka: 'სან-მარინო' },
  { code: 'ST', ru: 'Сан-Томе и Принсипи', ka: 'სან-ტომე და პრინსიპი' },
  { code: 'SA', ru: 'Саудовская Аравия', ka: 'საუდის არაბეთი' },
  { code: 'MK', ru: 'Северная Македония', ka: 'ჩრდილოეთ მაკედონია' },
  { code: 'SC', ru: 'Сейшельские Острова', ka: 'სეიშელის კუნძულები' },
  { code: 'SN', ru: 'Сенегал', ka: 'სენეგალი' },
  { code: 'VC', ru: 'Сент-Винсент и Гренадины', ka: 'სენტ-ვინსენტი და გრენადინები' },
  { code: 'KN', ru: 'Сент-Китс и Невис', ka: 'სენტ-კიტსი და ნევისი' },
  { code: 'LC', ru: 'Сент-Люсия', ka: 'სენტ-ლუსია' },
  { code: 'RS', ru: 'Сербия', ka: 'სერბეთი' },
  { code: 'SG', ru: 'Сингапур', ka: 'სინგაპური' },
  { code: 'SY', ru: 'Сирия', ka: 'სირია' },
  { code: 'SK', ru: 'Словакия', ka: 'სლოვაკეთი' },
  { code: 'SI', ru: 'Словения', ka: 'სლოვენია' },
  { code: 'SB', ru: 'Соломоновы Острова', ka: 'სოლომონის კუნძულები' },
  { code: 'SO', ru: 'Сомали', ka: 'სომალი' },
  { code: 'SD', ru: 'Судан', ka: 'სუდანი' },
  { code: 'SR', ru: 'Суринам', ka: 'სურინამი' },
  { code: 'US', ru: 'США', ka: 'აშშ' },
  { code: 'SL', ru: 'Сьерра-Леоне', ka: 'სიერა-ლეონე' },
  { code: 'TJ', ru: 'Таджикистан', ka: 'ტაჯიკეთი' },
  { code: 'TH', ru: 'Таиланд', ka: 'ტაილანდი' },
  { code: 'TZ', ru: 'Танзания', ka: 'ტანზანია' },
  { code: 'TG', ru: 'Того', ka: 'ტოგო' },
  { code: 'TO', ru: 'Тонга', ka: 'ტონგა' },
  { code: 'TT', ru: 'Тринидад и Тобаго', ka: 'ტრინიდადი და ტობაგო' },
  { code: 'TV', ru: 'Тувалу', ka: 'ტუვალუ' },
  { code: 'TN', ru: 'Тунис', ka: 'ტუნისი' },
  { code: 'TM', ru: 'Туркменистан', ka: 'თურქმენეთი' },
  { code: 'TR', ru: 'Турция', ka: 'თურქეთი' },
  { code: 'UG', ru: 'Уганда', ka: 'უგანდა' },
  { code: 'UZ', ru: 'Узбекистан', ka: 'უზბეკეთი' },
  { code: 'UA', ru: 'Украина', ka: 'უკრაინა' },
  { code: 'UY', ru: 'Уругвай', ka: 'ურუგვაი' },
  { code: 'FM', ru: 'Федеративные Штаты Микронезии', ka: 'მიკრონეზია' },
  { code: 'FJ', ru: 'Фиджи', ka: 'ფიჯი' },
  { code: 'PH', ru: 'Филиппины', ka: 'ფილიპინები' },
  { code: 'FI', ru: 'Финляндия', ka: 'ფინეთი' },
  { code: 'FR', ru: 'Франция', ka: 'საფრანგეთი' },
  { code: 'HR', ru: 'Хорватия', ka: 'ხორვატია' },
  { code: 'CF', ru: 'ЦАР', ka: 'ცენტრალური აფრიკის რესპუბლიკა' },
  { code: 'TD', ru: 'Чад', ka: 'ჩადი' },
  { code: 'ME', ru: 'Черногория', ka: 'ჩერნოგორია' },
  { code: 'CZ', ru: 'Чехия', ka: 'ჩეხეთი' },
  { code: 'CL', ru: 'Чили', ka: 'ჩილე' },
  { code: 'CH', ru: 'Швейцария', ka: 'შვეიცარია' },
  { code: 'SE', ru: 'Швеция', ka: 'შვედეთი' },
  { code: 'LK', ru: 'Шри-Ланка', ka: 'შრი-ლანკა' },
  { code: 'EC', ru: 'Эквадор', ka: 'ეკვადორი' },
  { code: 'GQ', ru: 'Экваториальная Гвинея', ka: 'ეკვატორული გვინეა' },
  { code: 'ER', ru: 'Эритрея', ka: 'ერიტრეა' },
  { code: 'SZ', ru: 'Эсватини', ka: 'ესვატინი' },
  { code: 'EE', ru: 'Эстония', ka: 'ესტონეთი' },
  { code: 'ET', ru: 'Эфиопия', ka: 'ეთიოპია' },
  { code: 'ZA', ru: 'ЮАР', ka: 'სამხრეთ აფრიკა' },
  { code: 'SS', ru: 'Южный Судан', ka: 'სამხრეთ სუდანი' },
  { code: 'JM', ru: 'Ямайка', ka: 'იამაიკა' },
  { code: 'JP', ru: 'Япония', ka: 'იაპონია' },
]

export function countryLabel(entry: CountryEntry, locale: 'ru' | 'ka'): string {
  return locale === 'ka' ? entry.ka : entry.ru
}

export function countriesSorted(locale: 'ru' | 'ka'): CountryEntry[] {
  return [...COUNTRIES].sort((a, b) =>
    countryLabel(a, locale).localeCompare(countryLabel(b, locale), locale === 'ka' ? 'ka' : 'ru'),
  )
}

/** Найти код по сохранённому названию (для старых записей и смены языка) */
export function resolveCountryCode(stored: string | undefined): string {
  if (!stored?.trim()) return ''
  const s = stored.trim()
  const hit = COUNTRIES.find((c) => c.ru === s || c.ka === s || c.code === s)
  return hit?.code ?? ''
}

export function countryLabelByCode(
  code: string | undefined,
  locale: 'ru' | 'ka',
): string {
  if (!code?.trim()) return ''
  const entry = COUNTRIES.find((c) => c.code === code)
  return entry ? countryLabel(entry, locale) : code
}

/** @deprecated — для миграции со старых текстовых названий */
export function countryLabelByStored(stored: string | undefined, locale: 'ru' | 'ka'): string {
  if (!stored?.trim()) return ''
  const code = resolveCountryCode(stored)
  return code ? countryLabelByCode(code, locale) : stored
}
